sudo: required

dist: trusty

services:
  - docker

language: node_js

node_js:
  - "node"

addons:
  chrome: stable

before_install:
  - docker build --rm --tag coda-mysql:latest ./mysql
  - docker build --rm --tag coda-drupal:latest ./drupal
  - docker run --mount src=mysql-data,dst=/var/lib/mysql --name drual-mysql -d coda-mysql:latest
  - docker run  --link drual-mysql:mysql --name drupal-app -d drupal coda-drupal:latest
  - nvm install latest
  
install:
  - npm install

script: node test
